project:
  type: website
  output-dir: docs

website:
  title: "Markus Kangur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - problems.qmd

format:
  html:
    html-math-method: mathml
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

